# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('apikey', models.CharField(max_length=100, null=True)),
                ('cbroker', models.CharField(max_length=50, null=True)),
                ('entity_type', models.CharField(max_length=50, null=True)),
                ('resource', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50, null=True)),
                ('ws_id', models.CharField(max_length=50, null=True)),
                ('entity_type', models.CharField(max_length=50, null=True)),
                ('protocol', models.CharField(max_length=50, null=True)),
                ('timezone', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
