# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170822_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
