# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workspace_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='name',
        ),
    ]
